title: Evan Machnic
author: Evan Machnic
email: emachnic@broadmac.net
description: > # this means to ignore newlines until "baseurl:"
  My name is Evan Machnic. I've been coding for the web since
  2003. I picked up Ruby on Rails starting in 2009 and I work
  full-time as a DevOps Engineer.

# social links
twitter_username: emachnic
github_username:  emachnic

show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
